name: "Bump H5P version"

description: "This action bumps the library version of a H5P project."

author: "Sindre Bøyum"

branding:
  icon: package
  color: blue

inputs:
  type:
    required: true
    description: The version type to update. Either `major`, `minor`, or `patch`. If `minor` is bumped, the patch version will be set to 0.

  working-directory:
    required: false
    description: The directory where the library.json file is located, relative to the Git project.
    default: "."

runs:
  using: "node16"
  main: "dist/index.js"
